### ISSUE TITLE
Direct "suggest change" link for blog posts?

### ISSUE THREAD

**Issue by SeanKilleen** [caseywatts/caseywatts-blog#2]
in #1  (whoa, I was the first PR? what?) I suggested a quick typo fix.

That made me think -- I had to hunt around for a little bit (go to your github, find the repo, search for the typo, find the MDX file).

On [my blog](https://SeanKilleen.com) I have a "Suggest an edit" button that is a concatenated link to the Markdown file that the post is sourced from.

> ![Example of the link to suggest an edit](https://github.com/user-attachments/assets/4bd00ca8-0899-4216-a779-e84e950e29fa)

My guess is you might benefit from something like this too for your MDX files if possible. I know I've gotten several quality suggestions based on having that link in place.

Feel free to close if you're not interested 👍 just wanted to drop the thought.

**Comment by caseywatts** [comment]
I like this idea!

I just added something similar to this [musical improv wiki](https://games.baltimoremusicalimprov.com/) - each article has a link to edit the source file (which I use via the new google docs markdown export ✨)

**Comment by caseywatts** [comment]
done! 👏
